language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: 
  - builddir="${TRAVIS_BUILD_DIR}/src/_build" 
  - mkdir -p ${builddir} 
  - cd ${builddir} 
  - cmake .. 
  - make  

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libstdc++-4.8-dev libboost-dev gnuradio libarmadillo-dev liblapack-dev libopenblas-dev gfortran libssl-dev libgflags-dev